/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class TestJNIByJVM */

#ifndef _Included_TestJNIByJVM
#define _Included_TestJNIByJVM
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     TestJNIByJVM
 * Method:    testJNI
 * Signature: (ID)I
 */
JNIEXPORT jint JNICALL Java_TestJNIByJVM_testJNI
  (JNIEnv *, jobject, jint, jdouble);

#ifdef __cplusplus
}
#endif
#endif
